name: 自动化打包软件

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: pyinstaller -F -c -n rogue -i resources/app.icns app.py && cd dist/ && zip rogue.zip rogue
            OUT_FILE_NAME: rogue.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -c -n rogue -i resources/app.ico app.py
            OUT_FILE_NAME: rogue.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/${{ matrix.OUT_FILE_NAME}}

